// Every public component has a live example. The inventory test keeps this list complete.
export const entries = [
  { name: 'Button', file: 'Button.tsx', group: 'Inputs' },
  { name: 'ButtonSpecimen', file: 'Button.tsx', group: 'Inputs' },
  { name: 'Checkbox', file: 'Choice.tsx', group: 'Inputs' },
  { name: 'Radio', file: 'Choice.tsx', group: 'Inputs' },
  { name: 'TextArea', file: 'TextArea.tsx', group: 'Inputs' },
  { name: 'TextInput', file: 'TextInput.tsx', group: 'Inputs' },
  { name: 'NumberInput', file: 'NumberInput.tsx', group: 'Inputs' },
  { name: 'Spinner', file: 'Spinner.tsx', group: 'Inputs' },
  { name: 'Dropdown', file: 'Dropdown.tsx', group: 'Inputs' },
  { name: 'ColorSwatch', file: 'ColorSwatch.tsx', group: 'Inputs' },
  { name: 'ListView', file: 'ListView.tsx', group: 'Collections' },
  { name: 'TreeView', file: 'TreeView.tsx', group: 'Collections' },
  { name: 'ColumnHeader', file: 'SurfaceBox.tsx', group: 'Collections' },
  { name: 'Pane', file: 'Pane.tsx', group: 'Collections' },
  { name: 'SplitPane', file: 'SplitPane.tsx', group: 'Collections' },
  { name: 'ScrollArea', file: 'ScrollArea.tsx', group: 'Collections' },
  { name: 'Scrollbar', file: 'Scrollbar.tsx', group: 'Collections' },
  { name: 'Menu', file: 'Menu.tsx', group: 'Menus' },
  { name: 'MenuItem', file: 'Menu.tsx', group: 'Menus' },
  { name: 'MenuSeparator', file: 'Menu.tsx', group: 'Menus' },
  { name: 'MenuBar', file: 'MenuBar.tsx', group: 'Menus' },
  { name: 'Toolbar', file: 'Toolbar.tsx', group: 'Menus' },
  { name: 'ToolbarButton', file: 'Toolbar.tsx', group: 'Menus' },
  { name: 'Window', file: 'Window.tsx', group: 'Windows' },
  { name: 'WindowChrome', file: 'Window.tsx', group: 'Windows' },
  { name: 'WindowFrame', file: 'WindowChrome.tsx', group: 'Windows' },
  { name: 'TitleBar', file: 'WindowChrome.tsx', group: 'Windows' },
  { name: 'CaptionButton', file: 'CaptionButton.tsx', group: 'Windows' },
  { name: 'Dialog', file: 'Dialog.tsx', group: 'Windows' },
  { name: 'StatusBar', file: 'StatusBar.tsx', group: 'Windows' },
  { name: 'StatusField', file: 'StatusBar.tsx', group: 'Windows' },
  { name: 'SizeGrip', file: 'SizeGrip.tsx', group: 'Windows' },
  { name: 'WindowTracking', file: 'WindowTracking.tsx', group: 'Windows' },
  { name: 'Taskbar', file: 'Taskbar.tsx', group: 'Desktop' },
  { name: 'TaskbarButton', file: 'TaskbarButton.tsx', group: 'Desktop' },
  { name: 'StartMenu', file: 'StartMenu.tsx', group: 'Desktop' },
  { name: 'IconButton', file: 'IconButton.tsx', group: 'Desktop' },
  { name: 'NativeText', file: 'NativeText.tsx', group: 'Presentation' },
  { name: 'Label', file: 'Label.tsx', group: 'Presentation' },
  { name: 'Icon', file: 'Icon.tsx', group: 'Presentation' },
  { name: 'SurfaceBox', file: 'SurfaceBox.tsx', group: 'Presentation' },
  { name: 'PixelScale', file: 'PixelScale.tsx', group: 'Presentation' },
] as const
export type ComponentName = typeof entries[number]['name']
export type StoryProps = { scale: number }
