"""Encode every original bitmap font strike as integer-rectangle WOFF outlines."""
from pathlib import Path
import hashlib
import json
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen

ROOT = Path(__file__).resolve().parents[1]
sources = json.loads((ROOT / 'src/fonts/bitmap-fonts.json').read_text())
css = []
for key, source in sources.items():
    family, size = key.split(':')
    for bold in ([False, True] if family == 'ms-sans-serif' else [False]):
        weight = 700 if bold or source['weight'] == 'bold' else 400
        glyph_data = source['glyphs']
        if bold:
            glyph_data = {char: {'advance': glyph['advance'] + 1, 'rows': [
                ''.join('1' if (x < len(row) and row[x] == '1') or (x > 0 and row[x - 1] == '1') else '0' for x in range(len(row) + 1)) for row in glyph['rows']
            ]} for char, glyph in glyph_data.items()}
        unit, height, baseline = 64, source['height'], source['baseline']
        order = ['.notdef'] + [f'uni{ord(char):04X}' for char in glyph_data]
        glyphs, metrics = {}, {}
        for name, glyph in [('.notdef', glyph_data['?'])] + [(f'uni{ord(char):04X}', glyph) for char, glyph in glyph_data.items()]:
            pen = TTGlyphPen(None)
            for y, row in enumerate(glyph['rows']):
                x = 0
                while x < len(row):
                    if row[x] != '1':
                        x += 1
                        continue
                    start = x
                    while x < len(row) and row[x] == '1':
                        x += 1
                    left, right = start * unit, x * unit
                    top, bottom = (baseline - y) * unit, (baseline - y - 1) * unit
                    pen.moveTo((left, bottom)); pen.lineTo((left, top)); pen.lineTo((right, top)); pen.lineTo((right, bottom)); pen.closePath()
            outline = pen.glyph()
            glyphs[name] = outline
            outline.recalcBounds(None)
            metrics[name] = (glyph['advance'] * unit, getattr(outline, 'xMin', 0))
        name = 'Chat95 MS Sans Serif' if key == 'ms-sans-serif:8' else f'Chat95 {family} {size}'
        filename = f'{family}-{size}' + ('-bold' if bold else '')
        font = FontBuilder(height * unit, isTTF=True)
        font.setupGlyphOrder(order)
        font.setupCharacterMap({ord(char): f'uni{ord(char):04X}' for char in glyph_data})
        font.setupGlyf(glyphs)
        font.setupHorizontalMetrics(metrics)
        font.setupHorizontalHeader(ascent=baseline * unit, descent=-(height - baseline) * unit, lineGap=0)
        font.setupNameTable({'familyName': name, 'styleName': 'Bold' if weight == 700 else 'Regular', 'uniqueFontIdentifier': f'Chat95-{filename}-Native', 'fullName': f'{name} {weight}', 'psName': f'Chat95-{filename}', 'version': 'Version 1.0', 'copyright': source['copyright']})
        font.setupOS2(sTypoAscender=baseline * unit, sTypoDescender=-(height - baseline) * unit, sTypoLineGap=0, usWinAscent=baseline * unit, usWinDescent=(height - baseline) * unit, fsSelection=0x20 if weight == 700 else 0x40, usWeightClass=weight)
        font.setupPost(); font.setupMaxp()
        font.font['head'].created = font.font['head'].modified = 3025069200
        font.font['head'].macStyle = 1 if weight == 700 else 0
        font.font.recalcTimestamp = False
        font.font.flavor = 'woff'
        font_path = ROOT / f'public/fonts/{filename}.woff'
        font.save(font_path)
        # Updating public assets alone does not invalidate a loaded font face.
        # Change the CSS URL whenever its bytes change, including during HMR.
        version = hashlib.sha256(font_path.read_bytes()).hexdigest()[:12]
        css.append(f"@font-face {{ font-family: '{name}'; src: url('/fonts/{filename}.woff?v={version}') format('woff'); font-style: normal; font-weight: {weight}; font-display: block; }}")
        print(f'{filename}: {len(glyph_data)} glyphs, {height}px em, baseline {baseline}px')
(ROOT / 'src/components/fonts.css').write_text('/* Generated by scripts/build-web-font.py. */\n' + '\n'.join(css) + '\n')
