export type IconSize = 16 | 32

const iconAssets: Record<string, string> = {
  '0-16': new URL('./assets/icons/0-16.png', import.meta.url).href,
  '0-32': new URL('./assets/icons/0-32.png', import.meta.url).href,
  '1-16': new URL('./assets/icons/1-16.png', import.meta.url).href,
  '1-32': new URL('./assets/icons/1-32.png', import.meta.url).href,
  '2-16': new URL('./assets/icons/2-16.png', import.meta.url).href,
  '2-32': new URL('./assets/icons/2-32.png', import.meta.url).href,
  '3-16': new URL('./assets/icons/3-16.png', import.meta.url).href,
  '3-32': new URL('./assets/icons/3-32.png', import.meta.url).href,
  '4-16': new URL('./assets/icons/4-16.png', import.meta.url).href,
  '4-32': new URL('./assets/icons/4-32.png', import.meta.url).href,
  '5-16': new URL('./assets/icons/5-16.png', import.meta.url).href,
  '5-32': new URL('./assets/icons/5-32.png', import.meta.url).href,
  '6-16': new URL('./assets/icons/6-16.png', import.meta.url).href,
  '6-32': new URL('./assets/icons/6-32.png', import.meta.url).href,
  '7-16': new URL('./assets/icons/7-16.png', import.meta.url).href,
  '7-32': new URL('./assets/icons/7-32.png', import.meta.url).href,
  '8-16': new URL('./assets/icons/8-16.png', import.meta.url).href,
  '8-32': new URL('./assets/icons/8-32.png', import.meta.url).href,
  '9-16': new URL('./assets/icons/9-16.png', import.meta.url).href,
  '9-32': new URL('./assets/icons/9-32.png', import.meta.url).href,
  '10-16': new URL('./assets/icons/10-16.png', import.meta.url).href,
  '10-32': new URL('./assets/icons/10-32.png', import.meta.url).href,
  '11-16': new URL('./assets/icons/11-16.png', import.meta.url).href,
  '11-32': new URL('./assets/icons/11-32.png', import.meta.url).href,
  '12-16': new URL('./assets/icons/12-16.png', import.meta.url).href,
  '12-32': new URL('./assets/icons/12-32.png', import.meta.url).href,
  '13-16': new URL('./assets/icons/13-16.png', import.meta.url).href,
  '13-32': new URL('./assets/icons/13-32.png', import.meta.url).href,
  '14-16': new URL('./assets/icons/14-16.png', import.meta.url).href,
  '14-32': new URL('./assets/icons/14-32.png', import.meta.url).href,
  '15-16': new URL('./assets/icons/15-16.png', import.meta.url).href,
  '15-32': new URL('./assets/icons/15-32.png', import.meta.url).href,
  '16-16': new URL('./assets/icons/16-16.png', import.meta.url).href,
  '16-32': new URL('./assets/icons/16-32.png', import.meta.url).href,
  '17-16': new URL('./assets/icons/17-16.png', import.meta.url).href,
  '17-32': new URL('./assets/icons/17-32.png', import.meta.url).href,
  '18-16': new URL('./assets/icons/18-16.png', import.meta.url).href,
  '18-32': new URL('./assets/icons/18-32.png', import.meta.url).href,
  '19-16': new URL('./assets/icons/19-16.png', import.meta.url).href,
  '19-32': new URL('./assets/icons/19-32.png', import.meta.url).href,
  '20-16': new URL('./assets/icons/20-16.png', import.meta.url).href,
  '20-32': new URL('./assets/icons/20-32.png', import.meta.url).href,
  '21-16': new URL('./assets/icons/21-16.png', import.meta.url).href,
  '21-32': new URL('./assets/icons/21-32.png', import.meta.url).href,
  '22-16': new URL('./assets/icons/22-16.png', import.meta.url).href,
  '22-32': new URL('./assets/icons/22-32.png', import.meta.url).href,
  '23-16': new URL('./assets/icons/23-16.png', import.meta.url).href,
  '23-32': new URL('./assets/icons/23-32.png', import.meta.url).href,
  '24-16': new URL('./assets/icons/24-16.png', import.meta.url).href,
  '24-32': new URL('./assets/icons/24-32.png', import.meta.url).href,
  '25-16': new URL('./assets/icons/25-16.png', import.meta.url).href,
  '25-32': new URL('./assets/icons/25-32.png', import.meta.url).href,
  '26-16': new URL('./assets/icons/26-16.png', import.meta.url).href,
  '26-32': new URL('./assets/icons/26-32.png', import.meta.url).href,
}

export function numberedIconUrl(index: number, size: IconSize) {
  return iconAssets[`${index}-${size}`] ?? ''
}

export const startFlagUrl = new URL('./assets/icons/start-flag.png', import.meta.url).href

const cursorAssets: Record<string, string> = {
  'arrow-1': new URL('./assets/cursors/arrow.png', import.meta.url).href,
  'arrow-2': new URL('./assets/cursors/scaled/arrow-2.png', import.meta.url).href,
  'arrow-3': new URL('./assets/cursors/scaled/arrow-3.png', import.meta.url).href,
  'arrow-4': new URL('./assets/cursors/scaled/arrow-4.png', import.meta.url).href,
  'arrow-5': new URL('./assets/cursors/scaled/arrow-5.png', import.meta.url).href,
  'arrow-6': new URL('./assets/cursors/scaled/arrow-6.png', import.meta.url).href,
  'arrow-7': new URL('./assets/cursors/scaled/arrow-7.png', import.meta.url).href,
  'arrow-8': new URL('./assets/cursors/scaled/arrow-8.png', import.meta.url).href,
  'arrow-9': new URL('./assets/cursors/scaled/arrow-9.png', import.meta.url).href,
  'arrow-10': new URL('./assets/cursors/scaled/arrow-10.png', import.meta.url).href,
  'arrow-11': new URL('./assets/cursors/scaled/arrow-11.png', import.meta.url).href,
  'arrow-12': new URL('./assets/cursors/scaled/arrow-12.png', import.meta.url).href,
  'arrow-13': new URL('./assets/cursors/scaled/arrow-13.png', import.meta.url).href,
  'arrow-14': new URL('./assets/cursors/scaled/arrow-14.png', import.meta.url).href,
  'arrow-15': new URL('./assets/cursors/scaled/arrow-15.png', import.meta.url).href,
  'arrow-16': new URL('./assets/cursors/scaled/arrow-16.png', import.meta.url).href,
  'ibeam-1': new URL('./assets/cursors/ibeam.png', import.meta.url).href,
  'ibeam-2': new URL('./assets/cursors/scaled/ibeam-2.png', import.meta.url).href,
  'ibeam-3': new URL('./assets/cursors/scaled/ibeam-3.png', import.meta.url).href,
  'ibeam-4': new URL('./assets/cursors/scaled/ibeam-4.png', import.meta.url).href,
  'ibeam-5': new URL('./assets/cursors/scaled/ibeam-5.png', import.meta.url).href,
  'ibeam-6': new URL('./assets/cursors/scaled/ibeam-6.png', import.meta.url).href,
  'ibeam-7': new URL('./assets/cursors/scaled/ibeam-7.png', import.meta.url).href,
  'ibeam-8': new URL('./assets/cursors/scaled/ibeam-8.png', import.meta.url).href,
  'ibeam-9': new URL('./assets/cursors/scaled/ibeam-9.png', import.meta.url).href,
  'ibeam-10': new URL('./assets/cursors/scaled/ibeam-10.png', import.meta.url).href,
  'ibeam-11': new URL('./assets/cursors/scaled/ibeam-11.png', import.meta.url).href,
  'ibeam-12': new URL('./assets/cursors/scaled/ibeam-12.png', import.meta.url).href,
  'ibeam-13': new URL('./assets/cursors/scaled/ibeam-13.png', import.meta.url).href,
  'ibeam-14': new URL('./assets/cursors/scaled/ibeam-14.png', import.meta.url).href,
  'ibeam-15': new URL('./assets/cursors/scaled/ibeam-15.png', import.meta.url).href,
  'ibeam-16': new URL('./assets/cursors/scaled/ibeam-16.png', import.meta.url).href,
  'sizewe-1': new URL('./assets/cursors/sizewe.png', import.meta.url).href,
  'sizewe-2': new URL('./assets/cursors/scaled/sizewe-2.png', import.meta.url).href,
  'sizewe-3': new URL('./assets/cursors/scaled/sizewe-3.png', import.meta.url).href,
  'sizewe-4': new URL('./assets/cursors/scaled/sizewe-4.png', import.meta.url).href,
  'sizewe-5': new URL('./assets/cursors/scaled/sizewe-5.png', import.meta.url).href,
  'sizewe-6': new URL('./assets/cursors/scaled/sizewe-6.png', import.meta.url).href,
  'sizewe-7': new URL('./assets/cursors/scaled/sizewe-7.png', import.meta.url).href,
  'sizewe-8': new URL('./assets/cursors/scaled/sizewe-8.png', import.meta.url).href,
  'sizewe-9': new URL('./assets/cursors/scaled/sizewe-9.png', import.meta.url).href,
  'sizewe-10': new URL('./assets/cursors/scaled/sizewe-10.png', import.meta.url).href,
  'sizewe-11': new URL('./assets/cursors/scaled/sizewe-11.png', import.meta.url).href,
  'sizewe-12': new URL('./assets/cursors/scaled/sizewe-12.png', import.meta.url).href,
  'sizewe-13': new URL('./assets/cursors/scaled/sizewe-13.png', import.meta.url).href,
  'sizewe-14': new URL('./assets/cursors/scaled/sizewe-14.png', import.meta.url).href,
  'sizewe-15': new URL('./assets/cursors/scaled/sizewe-15.png', import.meta.url).href,
  'sizewe-16': new URL('./assets/cursors/scaled/sizewe-16.png', import.meta.url).href,
  'sizens-1': new URL('./assets/cursors/sizens.png', import.meta.url).href,
  'sizens-2': new URL('./assets/cursors/scaled/sizens-2.png', import.meta.url).href,
  'sizens-3': new URL('./assets/cursors/scaled/sizens-3.png', import.meta.url).href,
  'sizens-4': new URL('./assets/cursors/scaled/sizens-4.png', import.meta.url).href,
  'sizens-5': new URL('./assets/cursors/scaled/sizens-5.png', import.meta.url).href,
  'sizens-6': new URL('./assets/cursors/scaled/sizens-6.png', import.meta.url).href,
  'sizens-7': new URL('./assets/cursors/scaled/sizens-7.png', import.meta.url).href,
  'sizens-8': new URL('./assets/cursors/scaled/sizens-8.png', import.meta.url).href,
  'sizens-9': new URL('./assets/cursors/scaled/sizens-9.png', import.meta.url).href,
  'sizens-10': new URL('./assets/cursors/scaled/sizens-10.png', import.meta.url).href,
  'sizens-11': new URL('./assets/cursors/scaled/sizens-11.png', import.meta.url).href,
  'sizens-12': new URL('./assets/cursors/scaled/sizens-12.png', import.meta.url).href,
  'sizens-13': new URL('./assets/cursors/scaled/sizens-13.png', import.meta.url).href,
  'sizens-14': new URL('./assets/cursors/scaled/sizens-14.png', import.meta.url).href,
  'sizens-15': new URL('./assets/cursors/scaled/sizens-15.png', import.meta.url).href,
  'sizens-16': new URL('./assets/cursors/scaled/sizens-16.png', import.meta.url).href,
  'sizenwse-1': new URL('./assets/cursors/sizenwse.png', import.meta.url).href,
  'sizenwse-2': new URL('./assets/cursors/scaled/sizenwse-2.png', import.meta.url).href,
  'sizenwse-3': new URL('./assets/cursors/scaled/sizenwse-3.png', import.meta.url).href,
  'sizenwse-4': new URL('./assets/cursors/scaled/sizenwse-4.png', import.meta.url).href,
  'sizenwse-5': new URL('./assets/cursors/scaled/sizenwse-5.png', import.meta.url).href,
  'sizenwse-6': new URL('./assets/cursors/scaled/sizenwse-6.png', import.meta.url).href,
  'sizenwse-7': new URL('./assets/cursors/scaled/sizenwse-7.png', import.meta.url).href,
  'sizenwse-8': new URL('./assets/cursors/scaled/sizenwse-8.png', import.meta.url).href,
  'sizenwse-9': new URL('./assets/cursors/scaled/sizenwse-9.png', import.meta.url).href,
  'sizenwse-10': new URL('./assets/cursors/scaled/sizenwse-10.png', import.meta.url).href,
  'sizenwse-11': new URL('./assets/cursors/scaled/sizenwse-11.png', import.meta.url).href,
  'sizenwse-12': new URL('./assets/cursors/scaled/sizenwse-12.png', import.meta.url).href,
  'sizenwse-13': new URL('./assets/cursors/scaled/sizenwse-13.png', import.meta.url).href,
  'sizenwse-14': new URL('./assets/cursors/scaled/sizenwse-14.png', import.meta.url).href,
  'sizenwse-15': new URL('./assets/cursors/scaled/sizenwse-15.png', import.meta.url).href,
  'sizenwse-16': new URL('./assets/cursors/scaled/sizenwse-16.png', import.meta.url).href,
  'sizenesw-1': new URL('./assets/cursors/sizenesw.png', import.meta.url).href,
  'sizenesw-2': new URL('./assets/cursors/scaled/sizenesw-2.png', import.meta.url).href,
  'sizenesw-3': new URL('./assets/cursors/scaled/sizenesw-3.png', import.meta.url).href,
  'sizenesw-4': new URL('./assets/cursors/scaled/sizenesw-4.png', import.meta.url).href,
  'sizenesw-5': new URL('./assets/cursors/scaled/sizenesw-5.png', import.meta.url).href,
  'sizenesw-6': new URL('./assets/cursors/scaled/sizenesw-6.png', import.meta.url).href,
  'sizenesw-7': new URL('./assets/cursors/scaled/sizenesw-7.png', import.meta.url).href,
  'sizenesw-8': new URL('./assets/cursors/scaled/sizenesw-8.png', import.meta.url).href,
  'sizenesw-9': new URL('./assets/cursors/scaled/sizenesw-9.png', import.meta.url).href,
  'sizenesw-10': new URL('./assets/cursors/scaled/sizenesw-10.png', import.meta.url).href,
  'sizenesw-11': new URL('./assets/cursors/scaled/sizenesw-11.png', import.meta.url).href,
  'sizenesw-12': new URL('./assets/cursors/scaled/sizenesw-12.png', import.meta.url).href,
  'sizenesw-13': new URL('./assets/cursors/scaled/sizenesw-13.png', import.meta.url).href,
  'sizenesw-14': new URL('./assets/cursors/scaled/sizenesw-14.png', import.meta.url).href,
  'sizenesw-15': new URL('./assets/cursors/scaled/sizenesw-15.png', import.meta.url).href,
  'sizenesw-16': new URL('./assets/cursors/scaled/sizenesw-16.png', import.meta.url).href,
  'no-1': new URL('./assets/cursors/no.png', import.meta.url).href,
  'no-2': new URL('./assets/cursors/scaled/no-2.png', import.meta.url).href,
  'no-3': new URL('./assets/cursors/scaled/no-3.png', import.meta.url).href,
  'no-4': new URL('./assets/cursors/scaled/no-4.png', import.meta.url).href,
  'no-5': new URL('./assets/cursors/scaled/no-5.png', import.meta.url).href,
  'no-6': new URL('./assets/cursors/scaled/no-6.png', import.meta.url).href,
  'no-7': new URL('./assets/cursors/scaled/no-7.png', import.meta.url).href,
  'no-8': new URL('./assets/cursors/scaled/no-8.png', import.meta.url).href,
  'no-9': new URL('./assets/cursors/scaled/no-9.png', import.meta.url).href,
  'no-10': new URL('./assets/cursors/scaled/no-10.png', import.meta.url).href,
  'no-11': new URL('./assets/cursors/scaled/no-11.png', import.meta.url).href,
  'no-12': new URL('./assets/cursors/scaled/no-12.png', import.meta.url).href,
  'no-13': new URL('./assets/cursors/scaled/no-13.png', import.meta.url).href,
  'no-14': new URL('./assets/cursors/scaled/no-14.png', import.meta.url).href,
  'no-15': new URL('./assets/cursors/scaled/no-15.png', import.meta.url).href,
  'no-16': new URL('./assets/cursors/scaled/no-16.png', import.meta.url).href,
}

const nativeCursorAssets = {
  arrow: new URL('./assets/cursors/arrow.cur', import.meta.url).href,
  ibeam: new URL('./assets/cursors/ibeam.cur', import.meta.url).href,
  sizewe: new URL('./assets/cursors/sizewe.cur', import.meta.url).href,
  sizens: new URL('./assets/cursors/sizens.cur', import.meta.url).href,
  sizenwse: new URL('./assets/cursors/sizenwse.cur', import.meta.url).href,
  sizenesw: new URL('./assets/cursors/sizenesw.cur', import.meta.url).href,
  no: new URL('./assets/cursors/no.cur', import.meta.url).href,
} as const

export type CursorAssetName = keyof typeof nativeCursorAssets

export function cursorImageUrl(name: CursorAssetName, scale: number) {
  return cursorAssets[`${name}-${scale}`] ?? cursorAssets[`${name}-1`]
}

export function nativeCursorUrl(name: CursorAssetName) {
  return nativeCursorAssets[name]
}
